# Car Dheko

In [1]:
import pandas as pd
import ast
from pandas import json_normalize

# Function to normalize a column with JSON-like string data
def normalize(df, column_name):
    df[f"{column_name}_dict"] = df[column_name].apply(ast.literal_eval)
    return json_normalize(df[f"{column_name}_dict"])

# Function to extract key-value pairs from car overview data
def extract_key_value_dicts(details):
    if isinstance(details, list):
        return {df['key']: df['value'] for df in details}
    return {}

# Function to process car overview column
def process_car_overview(car_overview_df):
    car_overview_df.drop(columns=["bottomData"], inplace=True, axis=1)
    new_car_overview = car_overview_df['top'].apply(extract_key_value_dicts)
    return pd.json_normalize(new_car_overview)

# Function to extract key-value pairs from car features data
def extract_key_value_dicts1(details_1):
    if isinstance(details_1, list):
        return {i: df['value'] for i, df in enumerate(details_1) if 'value' in df}
    return {}


# Function to extract key-value pairs from car specs data
def extract_key_value_dicts2(details2):
    if isinstance(details2, list):
        return {df['key']: df['value'] for df in details2}
    return {}

# Function to process car specs column
def process_car_specs(car_specs_df):
    car_specs_df.drop(columns=["commonIcon"], inplace=True, axis=1)
    new_car_specs_top = car_specs_df["top"].apply(extract_key_value_dicts2)
    return pd.json_normalize(new_car_specs_top)

# Function to process specs data by index
def process_car_specs_data_by_index(new_car_specs_data, index, extract_func):
    specs_data = pd.json_normalize(new_car_specs_data[index])
    if 'list' in specs_data.columns:
        extracted_data = specs_data["list"].apply(extract_func)
        return pd.json_normalize(extracted_data)
    return pd.DataFrame()

# Main function to process car data for a specific city
def process_city_data(file_path, city_name):
    df_city = pd.read_excel(file_path)
    df_city.drop(columns=["car_links"], inplace=True, axis=1)

    # Process each column
    new_car_detail = normalize(df_city, "new_car_detail")
    new_car_overview = process_car_overview(normalize(df_city, "new_car_overview"))

    # Process specs column and data
    new_car_specs = normalize(df_city, "new_car_specs")
    new_car_specs_top = process_car_specs(new_car_specs)
    new_car_specs_data = pd.json_normalize(new_car_specs["data"])

    specs_list_1 = process_car_specs_data_by_index(new_car_specs_data, 0, extract_key_value_dicts2)
    specs_list_2 = process_car_specs_data_by_index(new_car_specs_data, 1, extract_key_value_dicts2)
    specs_list_3 = process_car_specs_data_by_index(new_car_specs_data, 2, extract_key_value_dicts2)

    # Combine data into final DataFrame
    df_city_cars = pd.concat([
        new_car_detail, new_car_overview, new_car_specs_top,
        specs_list_1, specs_list_2, specs_list_3
    ], axis=1)
    df_city_cars['City'] = city_name

    return df_city_cars

# Process data for bangalore_cars
df_bangalore_cars = process_city_data("bangalore_cars.xlsx", "bangalore")
df_bangalore_cars

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Alloy Wheel Size,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN,bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16,bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14,bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14,bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16,bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,...,5.9 metres,Ventilated Disc,Drum,176 Kmph,9.6 Seconds,"Tubeless,Radial",5,296-litres,17,bangalore
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,...,5.3 m,Ventilated Disc,Drum,177 kmph,12.1 seconds,"Tubeless, Radial",4,505 litres,16,bangalore
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,...,4.5 metres,Disc,Drum,164 Kmph,14.5 Seconds,"Tubeless,Radial",5,175-litres,NaN,bangalore
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,...,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,5,295-litres,16,bangalore
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,...,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,5,256-liters,14,bangalore

In [2]:
import pandas as pd
import ast
from pandas import json_normalize

# Function to normalize a column with JSON-like string data
def normalize(df, column_name):
    df[f"{column_name}_dict"] = df[column_name].apply(ast.literal_eval)
    return json_normalize(df[f"{column_name}_dict"])

# Function to extract key-value pairs from car overview data
def extract_key_value_dicts(details):
    if isinstance(details, list):
        return {df['key']: df['value'] for df in details}
    return {}

# Function to process car overview column
def process_car_overview(car_overview_df):
    car_overview_df.drop(columns=["bottomData"], inplace=True, axis=1)
    new_car_overview = car_overview_df['top'].apply(extract_key_value_dicts)
    return pd.json_normalize(new_car_overview)

# Function to extract key-value pairs from car features data
def extract_key_value_dicts1(details_1):
    if isinstance(details_1, list):
        return {i: df['value'] for i, df in enumerate(details_1) if 'value' in df}
    return {}


# Function to extract key-value pairs from car specs data
def extract_key_value_dicts2(details2):
    if isinstance(details2, list):
        return {df['key']: df['value'] for df in details2}
    return {}

# Function to process car specs column
def process_car_specs(car_specs_df):
    car_specs_df.drop(columns=["commonIcon"], inplace=True, axis=1)
    new_car_specs_top = car_specs_df["top"].apply(extract_key_value_dicts2)
    return pd.json_normalize(new_car_specs_top)

# Function to process specs data by index
def process_car_specs_data_by_index(new_car_specs_data, index, extract_func):
    specs_data = pd.json_normalize(new_car_specs_data[index])
    if 'list' in specs_data.columns:
        extracted_data = specs_data["list"].apply(extract_func)
        return pd.json_normalize(extracted_data)
    return pd.DataFrame()

# Main function to process car data for a specific city
def process_city_data(file_path, city_name):
    df_city = pd.read_excel(file_path)
    df_city.drop(columns=["car_links"], inplace=True, axis=1)

    # Process each column
    new_car_detail = normalize(df_city, "new_car_detail")
    new_car_overview = process_car_overview(normalize(df_city, "new_car_overview"))

    # Process specs column and data
    new_car_specs = normalize(df_city, "new_car_specs")
    new_car_specs_top = process_car_specs(new_car_specs)
    new_car_specs_data = pd.json_normalize(new_car_specs["data"])

    specs_list_1 = process_car_specs_data_by_index(new_car_specs_data, 0, extract_key_value_dicts2)
    specs_list_2 = process_car_specs_data_by_index(new_car_specs_data, 1, extract_key_value_dicts2)
    specs_list_3 = process_car_specs_data_by_index(new_car_specs_data, 2, extract_key_value_dicts2)

    # Combine data into final DataFrame
    df_city_cars = pd.concat([
        new_car_detail, new_car_overview, new_car_specs_top,
        specs_list_1, specs_list_2, specs_list_3
    ], axis=1)
    df_city_cars['City'] = city_name

    return df_city_cars

# Process data for chennai_cars
df_chennai_cars = process_city_data("chennai_cars.xlsx", "chennai")
df_chennai_cars

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Turning Radius,Top Speed,Acceleration,City
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,Disc,Drum,"Tubeless, Radial",16,5,392,NaN,NaN,NaN,chennai
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,Ventilated Disc,Drum,Tubeless Tyres,NaN,5,540-liters,4.5 metres,145 Kmph,15.7 Seconds,chennai
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,Disc,Drum,"Tubeless,Radial",16,5,336,5.0,NaN,11.7,chennai
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,Ventilated Disc,Drum,Tubeless,NaN,5,225-litres,4.7 metres,165 Kmph,14.3 Seconds,chennai
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,Disc,Drum,"Tubeless,Radial",15,5,354-litres,5.1 meters,172 Kmph,13.7 Seconds,chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,...,Disc,Drum,Tubeless,NaN,5,268-litres,4.8 Meters,NaN,NaN,chennai
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,...,Disc,Drum,"Tubeless,Radial",16,5,475-litres,5.2 metres,156 Kmph,13.9 Seconds,chennai
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,...,Disc,Drum,Tubeless Radial Tyres,16,5,350,5.1m,154.19 kmph,NaN,chennai
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,...,Disc,Disc,Tubeless Radial Tyres,18,5,615,5.75meters,NaN,NaN,chennai
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,...,Disc,Disc,Run-Flat,18,4,520,5.5 metres,226 Kmph,7.7 Seconds,chennai

In [3]:
import pandas as pd
import ast
from pandas import json_normalize

# Function to normalize a column with JSON-like string data
def normalize(df, column_name):
    df[f"{column_name}_dict"] = df[column_name].apply(ast.literal_eval)
    return json_normalize(df[f"{column_name}_dict"])

# Function to extract key-value pairs from car overview data
def extract_key_value_dicts(details):
    if isinstance(details, list):
        return {df['key']: df['value'] for df in details}
    return {}

# Function to process car overview column
def process_car_overview(car_overview_df):
    car_overview_df.drop(columns=["bottomData"], inplace=True, axis=1)
    new_car_overview = car_overview_df['top'].apply(extract_key_value_dicts)
    return pd.json_normalize(new_car_overview)

# Function to extract key-value pairs from car features data
def extract_key_value_dicts1(details_1):
    if isinstance(details_1, list):
        return {i: df['value'] for i, df in enumerate(details_1) if 'value' in df}
    return {}


# Function to extract key-value pairs from car specs data
def extract_key_value_dicts2(details2):
    if isinstance(details2, list):
        return {df['key']: df['value'] for df in details2}
    return {}

# Function to process car specs column
def process_car_specs(car_specs_df):
    car_specs_df.drop(columns=["commonIcon"], inplace=True, axis=1)
    new_car_specs_top = car_specs_df["top"].apply(extract_key_value_dicts2)
    return pd.json_normalize(new_car_specs_top)

# Function to process specs data by index
def process_car_specs_data_by_index(new_car_specs_data, index, extract_func):
    specs_data = pd.json_normalize(new_car_specs_data[index])
    if 'list' in specs_data.columns:
        extracted_data = specs_data["list"].apply(extract_func)
        return pd.json_normalize(extracted_data)
    return pd.DataFrame()

# Main function to process car data for a specific city
def process_city_data(file_path, city_name):
    df_city = pd.read_excel(file_path)
    df_city.drop(columns=["car_links"], inplace=True, axis=1)

    # Process each column
    new_car_detail = normalize(df_city, "new_car_detail")
    new_car_overview = process_car_overview(normalize(df_city, "new_car_overview"))

    # Process specs column and data
    new_car_specs = normalize(df_city, "new_car_specs")
    new_car_specs_top = process_car_specs(new_car_specs)
    new_car_specs_data = pd.json_normalize(new_car_specs["data"])

    specs_list_1 = process_car_specs_data_by_index(new_car_specs_data, 0, extract_key_value_dicts2)
    specs_list_2 = process_car_specs_data_by_index(new_car_specs_data, 1, extract_key_value_dicts2)
    specs_list_3 = process_car_specs_data_by_index(new_car_specs_data, 2, extract_key_value_dicts2)

    # Combine data into final DataFrame
    df_city_cars = pd.concat([
        new_car_detail, new_car_overview, new_car_specs_top,
        specs_list_1, specs_list_2, specs_list_3
    ], axis=1)
    df_city_cars['City'] = city_name

    return df_city_cars

# Process data for bangalore_cars
df_delhi_cars = process_city_data("delhi_cars.xlsx", "delhi")
df_delhi_cars

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Turning Radius,Top Speed,Acceleration,City
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,...,Disc,Disc,"Tubeless, Radial",17,5,433,NaN,NaN,NaN,delhi
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,...,Disc,Drum,Tubeless,NaN,5,400-litres,5.3 metres,165 Kmph,10.5 Seconds,delhi
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,...,Disc,Disc,"Tubeless,Radial",19,5,550-litres,NaN,217 Kmph,NaN,delhi
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,...,Disc,Drum,"Radial, Tubeless",NaN,5,268,4.8,NaN,NaN,delhi
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,...,Disc,Drum,Tubeless,NaN,5,400-litres,5.3 metres,165 Kmph,10.5 Seconds,delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,...,Ventilated Disc,Drum,"Tubeless,Radial",15,4,510,5.3 metres,195 Kmph,10 Seconds,delhi
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,...,Disc,Drum,"Tubeless, Radial",NaN,5,392,NaN,NaN,NaN,delhi
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,...,Disc,Drum,"Tubeless,Radial",16,4,465-litre,5.2 metres,196km/hr,10.5 Seconds,delhi
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,...,Disc,Drum,Tubeless,17,5,400,5.3 metres,160.58kmph,10.83 s,delhi
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,...,Disc,Disc,"Tubeless, Radial",19,5,NaN,NaN,NaN,NaN,delhi

In [4]:
import pandas as pd
import ast
from pandas import json_normalize

# Function to normalize a column with JSON-like string data
def normalize(df, column_name):
    df[f"{column_name}_dict"] = df[column_name].apply(ast.literal_eval)
    return json_normalize(df[f"{column_name}_dict"])

# Function to extract key-value pairs from car overview data
def extract_key_value_dicts(details):
    if isinstance(details, list):
        return {df['key']: df['value'] for df in details}
    return {}

# Function to process car overview column
def process_car_overview(car_overview_df):
    car_overview_df.drop(columns=["bottomData"], inplace=True, axis=1)
    new_car_overview = car_overview_df['top'].apply(extract_key_value_dicts)
    return pd.json_normalize(new_car_overview)

# Function to extract key-value pairs from car features data
def extract_key_value_dicts1(details_1):
    if isinstance(details_1, list):
        return {i: df['value'] for i, df in enumerate(details_1) if 'value' in df}
    return {}


# Function to extract key-value pairs from car specs data
def extract_key_value_dicts2(details2):
    if isinstance(details2, list):
        return {df['key']: df['value'] for df in details2}
    return {}

# Function to process car specs column
def process_car_specs(car_specs_df):
    car_specs_df.drop(columns=["commonIcon"], inplace=True, axis=1)
    new_car_specs_top = car_specs_df["top"].apply(extract_key_value_dicts2)
    return pd.json_normalize(new_car_specs_top)

# Function to process specs data by index
def process_car_specs_data_by_index(new_car_specs_data, index, extract_func):
    specs_data = pd.json_normalize(new_car_specs_data[index])
    if 'list' in specs_data.columns:
        extracted_data = specs_data["list"].apply(extract_func)
        return pd.json_normalize(extracted_data)
    return pd.DataFrame()

# Main function to process car data for a specific city
def process_city_data(file_path, city_name):
    df_city = pd.read_excel(file_path)
    df_city.drop(columns=["car_links"], inplace=True, axis=1)

    # Process each column
    new_car_detail = normalize(df_city, "new_car_detail")
    new_car_overview = process_car_overview(normalize(df_city, "new_car_overview"))

    # Process specs column and data
    new_car_specs = normalize(df_city, "new_car_specs")
    new_car_specs_top = process_car_specs(new_car_specs)
    new_car_specs_data = pd.json_normalize(new_car_specs["data"])

    specs_list_1 = process_car_specs_data_by_index(new_car_specs_data, 0, extract_key_value_dicts2)
    specs_list_2 = process_car_specs_data_by_index(new_car_specs_data, 1, extract_key_value_dicts2)
    specs_list_3 = process_car_specs_data_by_index(new_car_specs_data, 2, extract_key_value_dicts2)

    # Combine data into final DataFrame
    df_city_cars = pd.concat([
        new_car_detail, new_car_overview, new_car_specs_top,
        specs_list_1, specs_list_2, specs_list_3
    ], axis=1)
    df_city_cars['City'] = city_name

    return df_city_cars

# Process data for bangalore_cars
df_hyderabad_cars = process_city_data("hyderabad_cars.xlsx", "hyderabad")
df_hyderabad_cars

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Top Speed,Acceleration,City
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,4.9,Disc,Drum,"Tubeless,Radial",R16,5,280,NaN,NaN,hyderabad
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,4.6 metres,Disc,Drum,Tubeless,NaN,5,215-litres,135 Kmph,19 Seconds,hyderabad
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,NaN,Disc,Drum,"Tubeless, Radial",NaN,5,NaN,NaN,NaN,hyderabad
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,4.9 meters,Disc,Drum,"Tubeless,Radial",16,5,339-litres,180 Kmph,12.36 seconds,hyderabad
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,NaN,Disc,Drum,"Radial, Tubeless",18,3,NaN,NaN,NaN,hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,...,5.6 metres,Disc & Caliper Type,Disc & Caliper Type,"Tubeless,Radial",17,5,NaN,175 kmph,12.5 Seconds,hyderabad
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,...,5.75 metres,Disc,Disc,"Tubeless,Radial",20,4,540-litres,250 Kmph,6.4 Seconds,hyderabad
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,...,5.6,Ventilated Disc,Ventilated Disc,"Tubeless, Runflat",R18,4,520-litres,235kmph,7.5,hyderabad
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,...,5.1m,Disc,Drum,Tubeless Radial Tyres,NaN,5,350,154.19 kmph,13.25 Seconds,hyderabad
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,...,5.4 metres,Ventilated Disc,Drum,"Tubeless,Radial",15,5,300-litres,155 Kmph,13.3 Seconds,hyderabad

In [5]:
import pandas as pd
import ast
from pandas import json_normalize

# Function to normalize a column with JSON-like string data
def normalize(df, column_name):
    df[f"{column_name}_dict"] = df[column_name].apply(ast.literal_eval)
    return json_normalize(df[f"{column_name}_dict"])

# Function to extract key-value pairs from car overview data
def extract_key_value_dicts(details):
    if isinstance(details, list):
        return {df['key']: df['value'] for df in details}
    return {}

# Function to process car overview column
def process_car_overview(car_overview_df):
    car_overview_df.drop(columns=["bottomData"], inplace=True, axis=1)
    new_car_overview = car_overview_df['top'].apply(extract_key_value_dicts)
    return pd.json_normalize(new_car_overview)

# Function to extract key-value pairs from car features data
def extract_key_value_dicts1(details_1):
    if isinstance(details_1, list):
        return {i: df['value'] for i, df in enumerate(details_1) if 'value' in df}
    return {}


# Function to extract key-value pairs from car specs data
def extract_key_value_dicts2(details2):
    if isinstance(details2, list):
        return {df['key']: df['value'] for df in details2}
    return {}

# Function to process car specs column
def process_car_specs(car_specs_df):
    car_specs_df.drop(columns=["commonIcon"], inplace=True, axis=1)
    new_car_specs_top = car_specs_df["top"].apply(extract_key_value_dicts2)
    return pd.json_normalize(new_car_specs_top)

# Function to process specs data by index
def process_car_specs_data_by_index(new_car_specs_data, index, extract_func):
    specs_data = pd.json_normalize(new_car_specs_data[index])
    if 'list' in specs_data.columns:
        extracted_data = specs_data["list"].apply(extract_func)
        return pd.json_normalize(extracted_data)
    return pd.DataFrame()

# Main function to process car data for a specific city
def process_city_data(file_path, city_name):
    df_city = pd.read_excel(file_path)
    df_city.drop(columns=["car_links"], inplace=True, axis=1)

    # Process each column
    new_car_detail = normalize(df_city, "new_car_detail")
    new_car_overview = process_car_overview(normalize(df_city, "new_car_overview"))

    # Process specs column and data
    new_car_specs = normalize(df_city, "new_car_specs")
    new_car_specs_top = process_car_specs(new_car_specs)
    new_car_specs_data = pd.json_normalize(new_car_specs["data"])

    specs_list_1 = process_car_specs_data_by_index(new_car_specs_data, 0, extract_key_value_dicts2)
    specs_list_2 = process_car_specs_data_by_index(new_car_specs_data, 1, extract_key_value_dicts2)
    specs_list_3 = process_car_specs_data_by_index(new_car_specs_data, 2, extract_key_value_dicts2)

    # Combine data into final DataFrame
    df_city_cars = pd.concat([
        new_car_detail, new_car_overview, new_car_specs_top,
        specs_list_1, specs_list_2, specs_list_3
    ], axis=1)
    df_city_cars['City'] = city_name

    return df_city_cars

# Process data for jaipur_cars
df_jaipur_cars = process_city_data("jaipur_cars.xlsx", "jaipur")
df_jaipur_cars

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,City
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,16,5,295-litres,jaipur
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,4.8,Disc,Drum,NaN,NaN,"Radial, Tubeless",NaN,5,268,jaipur
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",NaN,5,235-litres,jaipur
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,NaN,5,256,jaipur
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,4.6 metres,Ventilated Disc,Drum,152 kmph,18.6 Seconds,Tubeless Tyres,NaN,5,180-liters,jaipur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,4.85metres,Disc,Drum,NaN,NaN,"Tubeless,Radial",14,5,170-litres,jaipur
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,4.6m,Disc,Drum,137km/hr,17.7 seconds,"Tubeless,Radial",12,5,NaN,jaipur
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,NaN,Disc,Drum,NaN,NaN,"Tubeless, Radial",16,5,405,jaipur
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,4.6m,Disc,Drum,137km/hr,17.7 seconds,"Tubeless,Radial",12,5,NaN,jaipur
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,4.9 meters,Disc,Drum,180 Kmph,12.36 seconds,"Tubeless,Radial",NaN,5,339-litres,jaipur

In [6]:
import pandas as pd
import ast
from pandas import json_normalize

# Function to normalize a column with JSON-like string data
def normalize(df, column_name):
    df[f"{column_name}_dict"] = df[column_name].apply(ast.literal_eval)
    return json_normalize(df[f"{column_name}_dict"])

# Function to extract key-value pairs from car overview data
def extract_key_value_dicts(details):
    if isinstance(details, list):
        return {df['key']: df['value'] for df in details}
    return {}

# Function to process car overview column
def process_car_overview(car_overview_df):
    car_overview_df.drop(columns=["bottomData"], inplace=True, axis=1)
    new_car_overview = car_overview_df['top'].apply(extract_key_value_dicts)
    return pd.json_normalize(new_car_overview)

# Function to extract key-value pairs from car features data
def extract_key_value_dicts1(details_1):
    if isinstance(details_1, list):
        return {i: df['value'] for i, df in enumerate(details_1) if 'value' in df}
    return {}


# Function to extract key-value pairs from car specs data
def extract_key_value_dicts2(details2):
    if isinstance(details2, list):
        return {df['key']: df['value'] for df in details2}
    return {}

# Function to process car specs column
def process_car_specs(car_specs_df):
    car_specs_df.drop(columns=["commonIcon"], inplace=True, axis=1)
    new_car_specs_top = car_specs_df["top"].apply(extract_key_value_dicts2)
    return pd.json_normalize(new_car_specs_top)

# Function to process specs data by index
def process_car_specs_data_by_index(new_car_specs_data, index, extract_func):
    specs_data = pd.json_normalize(new_car_specs_data[index])
    if 'list' in specs_data.columns:
        extracted_data = specs_data["list"].apply(extract_func)
        return pd.json_normalize(extracted_data)
    return pd.DataFrame()

# Main function to process car data for a specific city
def process_city_data(file_path, city_name):
    df_city = pd.read_excel(file_path)
    df_city.drop(columns=["car_links"], inplace=True, axis=1)

    # Process each column
    new_car_detail = normalize(df_city, "new_car_detail")
    new_car_overview = process_car_overview(normalize(df_city, "new_car_overview"))

    # Process specs column and data
    new_car_specs = normalize(df_city, "new_car_specs")
    new_car_specs_top = process_car_specs(new_car_specs)
    new_car_specs_data = pd.json_normalize(new_car_specs["data"])

    specs_list_1 = process_car_specs_data_by_index(new_car_specs_data, 0, extract_key_value_dicts2)
    specs_list_2 = process_car_specs_data_by_index(new_car_specs_data, 1, extract_key_value_dicts2)
    specs_list_3 = process_car_specs_data_by_index(new_car_specs_data, 2, extract_key_value_dicts2)

    # Combine data into final DataFrame
    df_city_cars = pd.concat([
        new_car_detail, new_car_overview, new_car_specs_top,
        specs_list_1, specs_list_2, specs_list_3
    ], axis=1)
    df_city_cars['City'] = city_name

    return df_city_cars

# Process data for kolkata_cars
df_kolkata_cars = process_city_data("kolkata_cars.xlsx", "kolkata")
df_kolkata_cars

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Acceleration,Top Speed,City
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,...,5.5 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4,NaN,NaN,NaN,kolkata
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,...,4.7m,Disc,Drum,NaN,NaN,5,222,NaN,NaN,kolkata
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,...,NaN,Disc,Drum,"Tubeless, Radial",NaN,5,405,NaN,NaN,kolkata
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,...,5.20 m,Disc,Drum,"Tubeless,Radial",14,5,295 Lit,12.96 Sec,NaN,kolkata
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,...,5.9 metres,Ventilated Disc,Drum,"Tubeless,Radial",16,5,460-litres,8.2 Seconds,212 Kmph,kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,NaN,Ventilated Disc,Drum,"Tubeless, Radial",NaN,5,313,NaN,NaN,kolkata
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,4.6 metres,Solid Disc,Drum,Tubeless Tyres,NaN,5,177-litres,19 Seconds,140 kmph,kolkata
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,5.42 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4,475-litres,8.8 Seconds,230km/hr,kolkata
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,4.7 metres,Ventilated Disc,Drum,"Tubeless,Radial",14,5,236-liters,15 Seconds,156 Kmph,kolkata
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,5.2 metres,Disc,Drum,"Tubeless,Radial",16,5,410-litres,14.20 Seconds,168 Kmph,kolkata

In [8]:
# List of DataFrames
all_cities_car_data = [df_bangalore_cars,df_chennai_cars,df_delhi_cars,df_hyderabad_cars,df_jaipur_cars,df_kolkata_cars]

# 1. Rename Duplicate Columns to Ensure Unique Column Names
def rename_duplicate_columns(df):
    # Find duplicate columns
    cols = pd.Series(df.columns)
    for dup in cols[cols.duplicated()].unique():
        # Rename duplicates by appending a suffix '_1', '_2', etc.
        count = 0
        for i in range(len(cols)):
            if cols[i] == dup:
                count += 1
                if count > 1:
                    cols[i] = f"{dup}_{count-1}"
    df.columns = cols
    return df

# Apply the function to each DataFrame to ensure unique column names
all_cities_car_data = [rename_duplicate_columns(df) for df in all_cities_car_data]

# 2. Ensure All DataFrames Have the Same Columns
# Get the set of all unique column names across all DataFrames
all_columns = set()
for df in all_cities_car_data:
    all_columns.update(df.columns)

# Add missing columns to each DataFrame with NaN values
for df in all_cities_car_data:
    missing_cols = all_columns - set(df.columns)
    for col in missing_cols:
        df[col] = pd.NA  # or use np.nan if you prefer

# 3. Concatenate DataFrames with Outer Join
# Reset index for each DataFrame to avoid index conflicts
all_cities_car_data = [df.reset_index(drop=True) for df in all_cities_car_data]

# Concatenate all DataFrames along rows (axis=0) with outer join
combined_df = pd.concat(all_cities_car_data, axis=0, join='outer', ignore_index=True)

print(combined_df.shape)
combined_df.head()

(8369, 88)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Cargo Volumn,Alloy Wheel Size_2,City,Drive Type_1,Acceleration_1,Turning Radius_1,Top Speed_1,Front Brake Type_1,Gear Box_1,Rear Brake Type_1
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,235-litres,NaN,bangalore,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,352-litres,16,bangalore,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,242-litres,14,bangalore,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,407-litres,14,bangalore,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,353-litres,16,bangalore,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [9]:
combined_df.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'Registration Year',
       'Insurance Validity', 'Fuel Type', 'Seats', 'Kms Driven', 'RTO',
       'Ownership', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Mileage', 'Engine', 'Max Power', 'Torque',
       'Seats_1', 'Wheel Size', 'Color', 'Engine Type', 'Displacement',
       'Max Power_1', 'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Value Configuration', 'Fuel Suppy System', 'BoreX Stroke',
       'Compression Ratio', 'Turbo Charger', 'Super Charger',
       'Seating Capacity', 'Steering Type', 'Tyre Type', 'Alloy Wheel Size',
       'No Door Numbers', 'Length', 'Width', 'Height', 'Wheel Base',
       'Front Tread', 'Rear Tread', 'Kerb Weight', 'Gross Weight',
       'Ground Clearance Unladen', 'Seating Capacity_1', 'Steering Type_1',
       'Tyre Type_1', 'Alloy Wheel Size_1', 'No Door Numbers_1', 'Gear Box',
       'Drive Type', 'Seating Capacity_2', 'Steering Type_2', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type_2', 'No Door Numbers_2', 'Cargo Volumn',
       'Alloy Wheel Size_2', 'City', 'Drive Type_1', 'Acceleration_1',
       'Turning Radius_1', 'Top Speed_1', 'Front Brake Type_1', 'Gear Box_1',
       'Rear Brake Type_1'],
      dtype='object')

In [11]:
# drop column from dataframe
combined_df.drop(columns=["owner","centralVariantId","priceActual","priceSaving","priceFixedText","trendingText.imgUrl",
                          "trendingText.heading","trendingText.desc","Registration Year","RTO","Ownership",
                          "Engine Displacement","Seats","Wheel Size","Engine Type","Displacement","Max Power_1",
                          "Max Torque","No of Cylinder","Values per Cylinder","Values per Cylinder","Fuel Suppy System",
                          "BoreX Stroke","Compression Ratio","Turbo Charger","Super Charger","Seating Capacity",
                          "Tyre Type","Alloy Wheel Size","Height","Width","Wheel Base","Alloy Wheel Size_1",
                          "Front Tread","Rear Tread","Kerb Weight","Gross Weight","Ground Clearance Unladen",
                          "Seating Capacity_1","Seating Capacity_1","Tyre Type_1","No Door Numbers_1",
                          "Seating Capacity_2","Steering Type_2","Turning Radius","Front Brake Type","Rear Brake Type",
                          "Top Speed","Acceleration","Tyre Type_2","No Door Numbers_2","Alloy Wheel Size_2","Acceleration_1","Top Speed_1",
                          "Rear Brake Type_1","Front Brake Type_1","Gear Box_1","Turning Radius_1","variantName","Value Configuration","Steering Type",
                          "No Door Numbers","Length","Cargo Volumn","Drive Type_1","Torque","Steering Type_1","Year of Manufacture","Max Power","Transmission",
                          "Fuel Type","km"],inplace=True,axis=1)

In [12]:
combined_df

,it,ft,bt,transmission,ownerNo,oem,model,modelYear,price,Insurance Validity,Kms Driven,Mileage,Engine,Seats_1,Color,Gear Box,Drive Type,City
0,0,Petrol,Hatchback,Manual,3,Maruti,Maruti Celerio,2015,₹ 4 Lakh,Third Party insurance,"1,20,000 Kms",23.1 kmpl,998 CC,5,White,5 Speed,FWD,bangalore
1,0,Petrol,SUV,Manual,2,Ford,Ford Ecosport,2018,₹ 8.11 Lakh,Comprehensive,"32,706 Kms",17 kmpl,1497 CC,5,White,5 Speed,FWD,bangalore
2,0,Petrol,Hatchback,Manual,1,Tata,Tata Tiago,2018,₹ 5.85 Lakh,Comprehensive,"11,949 Kms",23.84 kmpl,1199 CC,5,Red,5 Speed,FWD,bangalore
3,0,Petrol,Sedan,Manual,1,Hyundai,Hyundai Xcent,2014,₹ 4.62 Lakh,Comprehensive,"17,794 Kms",19.1 kmpl,1197 CC,5,Others,5 Speed,FWD,bangalore
4,0,Diesel,SUV,Manual,1,Maruti,Maruti SX4 S Cross,2015,₹ 7.90 Lakh,Third Party insurance,"60,000 Kms",23.65 kmpl,1248 CC,5,Gray,5 Speed,FWD,bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,Manual,1,Maruti,Maruti Celerio,2022,₹ 5.10 Lakh,Third Party insurance,"10,000 Kms",25.24 kmpl,998 CC,5,Others,5-Speed,NaN,kolkata
8365,0,Petrol,Hatchback,Manual,1,Maruti,Maruti Alto 800,2014,₹ 1.80 Lakh,Third Party insurance,"1,20,000 Kms",22.74 kmpl,796 CC,5,Others,5 Speed,FWD,kolkata
8366,0,Petrol,Sedan,Automatic,3,Mercedes-Benz,Mercedes-Benz C-Class,2011,₹ 5.50 Lakh,Third Party insurance,"50,000 Kms",11.74 kmpl,1796 CC,5,Others,7 Speed,RWD,kolkata
8367,0,Petrol,Hatchback,Manual,1,Maruti,Maruti Ritz,2012,₹ 1.40 Lakh,Third Party insurance,"40,000 Kms",18.5 kmpl,1197 CC,5,Others,5 Speed,FWD,kolkata
8368,0,Diesel,SUV,Manual,2,Renault,Renault Duster,2017,₹ 5 Lakh,Third Party insurance,"1,20,000 Kms",19.72 kmpl,1461 CC,5,Others,6 Speed,AWD,kolkata

In [13]:
#convert dataframe to csv
combined_df.to_csv("ALL_CARS.csv",index=False)